# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yukikoo/Git/si4-uml

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yukikoo/Git/si4-uml

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yukikoo/Git/si4-uml/CMakeFiles /home/yukikoo/Git/si4-uml/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yukikoo/Git/si4-uml/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named si4_uml

# Build rule for target.
si4_uml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 si4_uml
.PHONY : si4_uml

# fast build rule for target.
si4_uml/fast:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/build
.PHONY : si4_uml/fast

ChargeFacePlotState.o: ChargeFacePlotState.cpp.o
.PHONY : ChargeFacePlotState.o

# target to build an object file
ChargeFacePlotState.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/ChargeFacePlotState.cpp.o
.PHONY : ChargeFacePlotState.cpp.o

ChargeFacePlotState.i: ChargeFacePlotState.cpp.i
.PHONY : ChargeFacePlotState.i

# target to preprocess a source file
ChargeFacePlotState.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/ChargeFacePlotState.cpp.i
.PHONY : ChargeFacePlotState.cpp.i

ChargeFacePlotState.s: ChargeFacePlotState.cpp.s
.PHONY : ChargeFacePlotState.s

# target to generate assembly for a file
ChargeFacePlotState.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/ChargeFacePlotState.cpp.s
.PHONY : ChargeFacePlotState.cpp.s

ChargeState.o: ChargeState.cpp.o
.PHONY : ChargeState.o

# target to build an object file
ChargeState.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/ChargeState.cpp.o
.PHONY : ChargeState.cpp.o

ChargeState.i: ChargeState.cpp.i
.PHONY : ChargeState.i

# target to preprocess a source file
ChargeState.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/ChargeState.cpp.i
.PHONY : ChargeState.cpp.i

ChargeState.s: ChargeState.cpp.s
.PHONY : ChargeState.s

# target to generate assembly for a file
ChargeState.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/ChargeState.cpp.s
.PHONY : ChargeState.cpp.s

EnRouteState.o: EnRouteState.cpp.o
.PHONY : EnRouteState.o

# target to build an object file
EnRouteState.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/EnRouteState.cpp.o
.PHONY : EnRouteState.cpp.o

EnRouteState.i: EnRouteState.cpp.i
.PHONY : EnRouteState.i

# target to preprocess a source file
EnRouteState.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/EnRouteState.cpp.i
.PHONY : EnRouteState.cpp.i

EnRouteState.s: EnRouteState.cpp.s
.PHONY : EnRouteState.s

# target to generate assembly for a file
EnRouteState.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/EnRouteState.cpp.s
.PHONY : EnRouteState.cpp.s

FigeState.o: FigeState.cpp.o
.PHONY : FigeState.o

# target to build an object file
FigeState.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/FigeState.cpp.o
.PHONY : FigeState.cpp.o

FigeState.i: FigeState.cpp.i
.PHONY : FigeState.i

# target to preprocess a source file
FigeState.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/FigeState.cpp.i
.PHONY : FigeState.cpp.i

FigeState.s: FigeState.cpp.s
.PHONY : FigeState.s

# target to generate assembly for a file
FigeState.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/FigeState.cpp.s
.PHONY : FigeState.cpp.s

Object.o: Object.cpp.o
.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i
.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s
.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Object.cpp.s
.PHONY : Object.cpp.s

Plot.o: Plot.cpp.o
.PHONY : Plot.o

# target to build an object file
Plot.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Plot.cpp.o
.PHONY : Plot.cpp.o

Plot.i: Plot.cpp.i
.PHONY : Plot.i

# target to preprocess a source file
Plot.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Plot.cpp.i
.PHONY : Plot.cpp.i

Plot.s: Plot.cpp.s
.PHONY : Plot.s

# target to generate assembly for a file
Plot.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Plot.cpp.s
.PHONY : Plot.cpp.s

Position.o: Position.cpp.o
.PHONY : Position.o

# target to build an object file
Position.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Position.cpp.o
.PHONY : Position.cpp.o

Position.i: Position.cpp.i
.PHONY : Position.i

# target to preprocess a source file
Position.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Position.cpp.i
.PHONY : Position.cpp.i

Position.s: Position.cpp.s
.PHONY : Position.s

# target to generate assembly for a file
Position.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Position.cpp.s
.PHONY : Position.cpp.s

Robot.o: Robot.cpp.o
.PHONY : Robot.o

# target to build an object file
Robot.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Robot.cpp.o
.PHONY : Robot.cpp.o

Robot.i: Robot.cpp.i
.PHONY : Robot.i

# target to preprocess a source file
Robot.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Robot.cpp.i
.PHONY : Robot.cpp.i

Robot.s: Robot.cpp.s
.PHONY : Robot.s

# target to generate assembly for a file
Robot.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/Robot.cpp.s
.PHONY : Robot.cpp.s

State.o: State.cpp.o
.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i
.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s
.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/State.cpp.s
.PHONY : State.cpp.s

VideFacePlotState.o: VideFacePlotState.cpp.o
.PHONY : VideFacePlotState.o

# target to build an object file
VideFacePlotState.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/VideFacePlotState.cpp.o
.PHONY : VideFacePlotState.cpp.o

VideFacePlotState.i: VideFacePlotState.cpp.i
.PHONY : VideFacePlotState.i

# target to preprocess a source file
VideFacePlotState.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/VideFacePlotState.cpp.i
.PHONY : VideFacePlotState.cpp.i

VideFacePlotState.s: VideFacePlotState.cpp.s
.PHONY : VideFacePlotState.s

# target to generate assembly for a file
VideFacePlotState.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/VideFacePlotState.cpp.s
.PHONY : VideFacePlotState.cpp.s

VideState.o: VideState.cpp.o
.PHONY : VideState.o

# target to build an object file
VideState.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/VideState.cpp.o
.PHONY : VideState.cpp.o

VideState.i: VideState.cpp.i
.PHONY : VideState.i

# target to preprocess a source file
VideState.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/VideState.cpp.i
.PHONY : VideState.cpp.i

VideState.s: VideState.cpp.s
.PHONY : VideState.s

# target to generate assembly for a file
VideState.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/VideState.cpp.s
.PHONY : VideState.cpp.s

demonstrator.o: demonstrator.cpp.o
.PHONY : demonstrator.o

# target to build an object file
demonstrator.cpp.o:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/demonstrator.cpp.o
.PHONY : demonstrator.cpp.o

demonstrator.i: demonstrator.cpp.i
.PHONY : demonstrator.i

# target to preprocess a source file
demonstrator.cpp.i:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/demonstrator.cpp.i
.PHONY : demonstrator.cpp.i

demonstrator.s: demonstrator.cpp.s
.PHONY : demonstrator.s

# target to generate assembly for a file
demonstrator.cpp.s:
	$(MAKE) -f CMakeFiles/si4_uml.dir/build.make CMakeFiles/si4_uml.dir/demonstrator.cpp.s
.PHONY : demonstrator.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... si4_uml"
	@echo "... ChargeFacePlotState.o"
	@echo "... ChargeFacePlotState.i"
	@echo "... ChargeFacePlotState.s"
	@echo "... ChargeState.o"
	@echo "... ChargeState.i"
	@echo "... ChargeState.s"
	@echo "... EnRouteState.o"
	@echo "... EnRouteState.i"
	@echo "... EnRouteState.s"
	@echo "... FigeState.o"
	@echo "... FigeState.i"
	@echo "... FigeState.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... Plot.o"
	@echo "... Plot.i"
	@echo "... Plot.s"
	@echo "... Position.o"
	@echo "... Position.i"
	@echo "... Position.s"
	@echo "... Robot.o"
	@echo "... Robot.i"
	@echo "... Robot.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... VideFacePlotState.o"
	@echo "... VideFacePlotState.i"
	@echo "... VideFacePlotState.s"
	@echo "... VideState.o"
	@echo "... VideState.i"
	@echo "... VideState.s"
	@echo "... demonstrator.o"
	@echo "... demonstrator.i"
	@echo "... demonstrator.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

